### ISSUE TITLE
3 июля

### ISSUE THREAD

**Issue by JAkutenshi** [somewaytolive/DoM_KopoJleBbl#1]
- [x] Требуются в спецификации UseCase и Class диаграммы 
- [x] Должен быть файл отчета, в котором есть вышеназванные диаграммы с пояснениями: 
   - [x] Для UC: объяснение как реалзиовано каждое действие из диаграммы и как оно отражено на интерфейсе пользователя, в какокм виде
   - [x] Для Class объяснение реалзиации сущностей и логическое обоснование связей между сущностями.
- [x] Прототип интерфейса с отрисовкой графа
- [x] pom.xml файл с зависимостями junit для тестирвоания и log4j2 для логгирования, а так же плагин для сборки в запускаемый jar архив (ссылка на нструкцию в дискорде в #java)
- [x] Реалзиован граф и алгоритм, и для всех методов написаны тесты на JUnit. Граф инициализирйте в тестах через setUp.
- [x] Все возможные исключительные ситуации (удаление у графа несуществующего узла) должны кидать исключения.
- [x] Обработка исключение включает в себя логгирование с описанием почем произошло исключение через log4j2
- [x] UC диаграмма обязательно включает следующие действия:
   - [x]  Генерация графа (кол-во узлов, ребер и мн-макс граница неотрицательных весов ребер)
   - [x] Чтение из файла
   - [x] Пошаговое исполнение с возможностью перезода в конечный результат алгоритма и обратно в начальное состояние одинм нажатием
   - [x] Взаимодействие с графом (модификация: удаление-добавление-обновление узлов-ребер-весов, перемешене узлов мышкой) через GUI
- [x] В отчте заполенн план работы, распределение ролей, алгоритм А\*, описание реализации и тестирования графа

**Comment by somewaytolive** [comment]
Добрый вечер, @JAkutenshi! 
План работы понятен за исключением 9 пункта, а имеено про алгоритм Борувки. Дело в том, что подготовку к летней практике мы начали заранее и первая версия проекта практичесски готова. Вы можете посмотреть на неё в ветке ver1. Реализованный алгоритм - А*. Задача следующая - поиск пути в лабиринте. По сути граф представлен в виде матрицы, преграды - вершины, которых не существует. Веса следующие - к соседям по вертикали и горизонтали можно дойти за 1, по диагонали - за sqrt(2). Как мы считаем, представление графа в виде матрицы для данной задачи наиболее удобно для пользователя, т.к. не приходится растягивать граф по экрану руками. Можем ли мы скорректировать план ввиду этих обстоятельств?

**Comment by JAkutenshi** [comment]
Ок, вижу в таблице Фирсова А*
